# ansible/inventory.gcp_compute.yml

plugin: gcp_compute
projects:
  # This correctly pulls the project ID from the CI environment.
  - "{{ lookup('env', 'CLOUDSDK_CORE_PROJECT') }}"

# [FIX] Changed auth_kind to 'application'.
# This tells the plugin to use the Application Default Credentials
# that the 'Authenticate to GCP' step has already set up.
auth_kind: application

# [FIX] Removed the service_account_contents line that was causing the error.

filters:
  - "status = RUNNING"

hostnames:
  - key: networkInterfaces[0].accessConfigs[0].natIP

compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP

keyed_groups:
  - key: labels['ansible-group']
    prefix: ''
